services:
  api:
    build:
      context: api
    expose:
      - "5555"
    networks:
      - webapp-network

  webapp:
    build:
      context: webapp
    ports:
      - "8080:8080"
    environment:
      - API_HOST=api
      - API_PORT=5555
    depends_on:
      - api
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
