[project]
authors = ["Adrielle Ayumi de Vasconcelos <adriayumi@gmail.com>"]
channels = ["conda-forge"]
name = "webapp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
requests = ">=2.32.3,<3"
pydantic = ">=2.10.4,<3"
flask = ">=3.1.0,<4"
waitress = ">=3.0.2,<4"
