[project]
authors = ["Adrielle Ayumi de Vasconcelos <adriayumi@gmail.com>"]
channels = ["conda-forge"]
name = "api"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
fastapi = ">=0.115.6,<0.116"
sqlmodel = ">=0.0.22,<0.0.23"
